spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/luyehua/config-repo.git
          username: luyehua@163.com
          password: abc5661663
          # git文件存放的路径
          basedir: /Users/luyehua/workspace/study/SpringCloud_Sell/config/basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka